### ISSUE TITLE
Add support for Sylius v1.2.0

### ISSUE THREAD

**Issue by pamil** [Sylius/ShopApiPlugin#278] opened 2018-06-08 08:46 UTC

**Comment by witrin** [comment] 2018-08-07 00:02
@pamil Is there a schedule for this?

**Comment by lchrusciel** [comment] 2018-08-07 06:46
I'm still looking for some time to spend on this, but feel free to help me with it :)

**Comment by witrin** [comment] 2018-08-07 07:26
@lchrusciel Can you give me some hints what is needed to be done?

**Comment by lchrusciel** [comment] 2018-08-07 07:59
Mostly this #281 should be merged, but there is some internal problem with translations. Also, we should run Sylius test suite to check if whole Sylius is working correctly.

**Comment by witrin** [comment] 2018-08-08 07:44
@lchrusciel Many of the errors were caused by `nelmio/alice` update. But there are still some open. Should I better post intermediate results or only final results?

**Comment by lchrusciel** [comment] 2018-08-08 09:36
If you only can, please share your fixes :) Feel free to push them directly to my branch

**Comment by witrin** [comment] 2018-08-08 18:32
@lchrusciel Sorry I meant push not post :D ...

**Comment by witrin** [comment] 2018-08-09 01:17
@lchrusciel 

1. JSON matcher does not working anymore.
2. Undefined index did not came up locally.
3. I  did not checked the failures right now.

**Comment by witrin** [comment] 2018-08-14 06:42
@lchrusciel @pamil Can't tell what's needed here https://github.com/Lakion/ApiTestCase/pull/125. Everything else is done! Could you please review?

**Comment by lchrusciel** [comment] 2018-08-14 11:13
I will verify it ASAP :)

**Closed** 2018-08-21 12:09 UTC
Labels: Maintenance
