### ISSUE TITLE
Extended sylius models

### ISSUE THREAD

**Issue by healerz** [Sylius/ShopApiPlugin#354] opened 2018-11-26 12:25 UTC
Hi everyone

I would like to discuss how to handle extended sylius models regarding the ShopApiPlugin.

### My assumption
If I add a property to a model (e.g. the order model) i see no convenient way, in the current state of the plugin, to enhance (read + write) the api to handle the additional property. Without copying and modifying the Controller, Request, Command and Handler classes, due to the final keyword.
In my eyes this would be a pity, because then i can't get updates / fixes of the affected action(s). In an extreme case, if i have a lot of modifications in base models, i end up in copying and rewriting most of the actions provided by this plugin.
I know, if it would be the "read" part only, i could handle it through the viewHandler.

If i'm wrong with my assumption please point me in the right direction :) **In this case you can stop reading :D**

#### 1. Copy and rewiring [project code only]
- Copy the involved Controller, Request, Command and Handler classes
- Add my property to all of them
- Overwrite the service definitions
- Overwrite the route definitions

#### 2. Remove the final keyword [project and plugin code]
- Remove the final keyword for controllers, requests, commands and handlers
- Maybe add a RequestFactory to be used in the controllers
- Extend (Controller), Request and Handler classes and add my property
- Rewire everything (services + routes)

#### 3. Add interfaces [project and plugin code]
- Add interfaces to requests and commands and type hint against them
- Implement the Interfaces in my custom Request and Command classes (probably decorate the existing ones, although it seems a bit pointless for these data holder classes unless the decorating part is done in a generic way)
- Create a RequestFactory to be used in the controllers
- Either replace the existing handler or decorate it
- Rewire everything

### "Conclusion"
Personally i would prefer option 2.
I would rather risk that my custom implementation breaks with updates / fixes than copying "everything" and not receiving updates and fixes.

Option 3 seems, in my eyes, a bit over engineered and depending on the exact implementation does not necessarily include updates and fixes. And again depending on the implementation, it does not prevent that something breaks with updates.

I'm looking forward to any kind of feedback! If you have other ideas / suggestions / solutions to my problem, let me know.
In case we come to a solution that requires changes in the plugin, i would be willing to create a poc :)

**Comment by mamazu** [comment] 2018-12-11 13:22
I'd suggest to use composition. So if you want to add a property to the request just wrap your own request around it.

**Comment by lchrusciel** [comment] 2019-01-11 15:02
Hello fellows, 
Sorry for such a late response. First of all, thanks for using ShopApi in the first place. I hope we will make it even better together. 

First of all, we need, to open all requests and command classes. Command classes should be replaced by interfaces as well. Removing `final` keyword from controllers and handlers will not bring any benefit.

Secondly, we may try to develop some generic handler for mapped request/handlers. Therefore it will reduce the amount of boilerplate required to write the code.

At last, we may try to optimize the amount of code even further, with query bus, and use generic implementation together with some XML mapping, so you don't need to carry about it. This step needs some deeper analysis thus. 

I hope, that I will come to you with some better plan next week.

**Comment by mamazu** [comment] 2019-01-29 14:32
I also added a little documentation for how to do it. #384

**Comment by CSchulz** [comment] 2019-06-01 22:39
@lchrusciel are there any news about the generic handler approach?
Perhaps we can copy the base controller setup from Sylius itself and adjust it to our needs to fit in this setup here.

**Comment by mamazu** [comment] 2019-06-02 11:06
I don't think the handler can be made more generic. The only thing I could imagine doing is that more handlers pass their information directly to Sylius and not define the logic themselves.

**Comment by flindblom-ohmy** [comment] 2019-08-14 13:22
Sorry for my ignorance, I'm still learning to work with Sylius. But the way I understand things based on this thread, there is no way to get extended parameters from the Shop API? 

Say I extend the Sylius Product class to include a "manufacturer" field, then the "manufacturer" parameter will not be included in the payload I get when doing, say, **GET /carts/<token>** ?

The solution is then what? To build my own API?

**Comment by mamazu** [comment] 2019-08-14 13:25
In this case you need to adapt the Product entity in Sylius to hold the data. Then in the API you can change the `ViewFactory` and the `View` for the cart and you should be good to go. If it is still not showing up, then you need to change the serialization.

**Comment by mamazu** [comment] 2019-08-14 13:26
You might want to have a look at the ongoing pull request that describes this in a little more detail: #514

**Comment by flindblom-ohmy** [comment] 2019-08-16 07:25
Thank you @mamazu for your response. Sadly I'm quite new to both Symphony and Sylius so I'm having trouble getting all this to work. I'm going to go through my process in detail below and hope somebody has the time to point out where I get things wrong. There may be a good laugh in there for experienced developers so it may be worth your while.

(And to clarify, the "manufacturer" parameter has been added to the Sylius Product class, I have a field for it working in admin and it is being saved properly to the database.)

***

When I invoke GET /shop-api/carts/(token)

The route is defined in `ShopApiPlugin/src/Resources/config/routing/cart.yml` which points to `sylius.shop_api_plugin.controller.cart.summarize_action`

Which is actually `ShopApiPlugin/src/Controller/Cart/SummarizeAction.php` which in turn knows that it is supposed to return a cart because a `CartViewRepositoryInterface` gets injected into the constructor.

And what actually gets injected is an instance of `ShopApiPlugin/src/ViewRepository/Cart/CartViewRepository.php` which uses its injected `CartViewFactoryInterface` to build the cart view.

That, in turn is an instance of `ShopApiPlugin/src/Factory/Cart/CartViewFactory.php` and the product list is built by a `CartItemViewFactoryInterface`.

Looking at `ShopApiPlugin/src/Factory/Cart/CartItemViewFactory.php` it uses the `ProductViewFactoryInterface` to build each product.

Next I'm in `ShopApiPlugin/src/Factory/Product/ProductViewFactory.php`. At this point the create() function is adding familiar things to $productView!

Getting close here, in `ShopApiPlugin/src/View/Product/ProductView.php` there's a list of these familiar attributes and now I'm pretty sure I'm on the right track.

***

So, first order of business, override `ShopApiPlugin/src/View/Product/ProductView.php` with my own `/src/View/Product/ExtendedProductView.php`. 

ProductView is not final so I can inherit everything and just add my "manufacturer" string in a really short class here.

Then in `/config/services.yaml` under `services`, to override the class, I add:

`Sylius\ShopApiPlugin\View\Product\ProductView:`
(spaces) `class: App\View\Product\ExtendedProductView`

***

Next things get a bit more uncertain, I have to use my own getManufacturer() function (that I've already added to the Sylius Product class) to get the manufacturer string into the view. 

So I assume I need to override `ProductViewFactory.php`, but this class is final so I can't inherit its functionality.

Instead I make a copy of `ShopApiPlugin/src/Factory/Product/ProductViewFactory.php` and put it in `/src/Factory/Product/ProductViewFactory.php`.

Change the name to `ExtendedProductViewFactory` and fix the namespace.

In the create function I add `$productView->manufacturer = $product->getManufacturer();` among the non-translated parameters.

Finally, in `/config/services.yaml`:

`Sylius\ShopApiPlugin\Factory\Product\ProductViewFactory:`
(spaces) `class: App\Factory\Product\ExtendedProductViewFactory`

***

However, I obviously still don't understand how all this works, because after doing all of the above (and clearing the cache for good measure) I still don't get the "manufacturer" parameter delivered when I invoke GET /shop-api/carts/(token)

There are no errors and the only thing my IDE is warning me about is that getManufacturer() is not defined in ProductInterface.

Where am I going wrong here, please?

**Comment by mamazu** [comment] 2019-08-16 11:32
Have you read the cookbook that i put into the merge request. There I (the documentation) explain in more details how to extend the `ViewFactory`. The concept is called decoration in Symfony which means wrapping one service inside another.

What you can do to check if the Factory is working correctly you can add a `dump` before returning the object in the factory to check if the property is correctly set.

The last part of the picture you are missing is the serializer. The Shop Api uses a serializer to turn the objects into strings. In there you also need to specify that the serializer adds this property to the JSON or XML response it is generating. Have a look here:

https://github.com/Sylius/ShopApiPlugin/blob/master/src/Resources/config/serializer/Product/ProductView.yml

**Comment by flindblom-ohmy** [comment] 2019-08-16 13:29
Thank you. I read the cookbook.md but I'm not wiser for it, sorry. 

Adding a dump() to the create() function in my ExtendedProductViewFactory does nothing, does that mean my class override is not working? What is the default behavior of the dump() function during ajax calls?

**Comment by mamazu** [comment] 2019-08-16 13:43
The dump Funktion just works like the php function var_dump. But if you're result isn't changing then the override didn't work. What does the `bin/console debug:container` say?

**Comment by flindblom-ohmy** [comment] 2019-08-16 13:47
`php bin/console debug:container | grep product_view
  sylius.shop_api_plugin.factory.detailed_product_view_factory                                                           Sylius\ShopApiPlugin\Factory\Product\DetailedProductViewFactory                                                                
  sylius.shop_api_plugin.factory.list_product_view_factory                                                               Sylius\ShopApiPlugin\Factory\Product\ListProductViewFactory                                                                    
  sylius.shop_api_plugin.factory.product_view_factory                                                                    Sylius\ShopApiPlugin\Factory\Product\ProductViewFactory`

Still using the default, hmmm.

**Comment by mamazu** [comment] 2019-08-16 13:50
How does your override look? (the yaml file)

**Comment by flindblom-ohmy** [comment] 2019-08-16 13:53
![services_yaml](https://user-images.githubusercontent.com/1257298/63172440-ffe13c80-c03d-11e9-8a66-8d0ab115698e.png)

**Comment by mamazu** [comment] 2019-08-16 13:56
You don't need to define the `ProductView` class in this file. It won't help. And for the factory you are using the wrong syntax for decorating:
    App\Factory\Product\ExtendedProductVariantFactory:
        decorates: sylius.shop_api_plugin.factory.detailed_product_view_factory

**Comment by mamazu** [comment] 2019-08-16 13:59
I assume you are using Symfony 4 then overwriting your view class would look like this:
```yml
shop_api:
  view_classes:
    product: 'App\View\Product\ExtendedProductVIew'
```

which is the content of a file under `config/packages/shop_api.yml`

**Comment by flindblom-ohmy** [comment] 2019-08-19 06:53
Thank you for clarifying the decorating syntax. I was using the first syntax on [this page](https://symfony.com/doc/current/service_container/service_decoration.html) because I figured I was replacing the whole service.

This is what I ended up doing:

```yaml
# Extend Shop API cart view to include custom parameters
App\Factory\Product\ExtendedProductViewFactory:
    arguments: ['@sylius.shop_api_plugin.factory.image_view_factory', '@sylius.shop_api_plugin.factory.limited_product_attribute_values_view_factory', '%sylius.shop_api.view.product.class%', '%sylius.shop_api.view.product_taxon.class%', '%locale%']
    decorates: sylius.shop_api_plugin.factory.product_view_factory
```
And now it's working! 

I am very thankful for your patience, I realize that all this would have been much easier if I had more experience with Symfony. After working with Laravel for many years this is my first Symfony project and I'm still not friends with all these yaml and xml files, but I'm getting there.

**Comment by flindblom-ohmy** [comment] 2019-08-19 09:36
So, even if I got it working "my way" I decided to go further and look at the "inner" factory that you mention in the cookbook, because now I kind of understand what is going on in that example, and it's a much more elegant solution.

First, just referring to the "inner" factory as you do in xml:

```xml
<argument type="service" id="app.factory.nice_total_view_factory.inner" />
```
doesn't work in yml:
```yaml
    App\Factory\Product\ExtendedProductViewFactory:
        arguments: ['@app.factory.product_view_factory.inner']
        decorates: sylius.shop_api_plugin.factory.product_view_factory
```
The above produces the following error:
```
The service "sylius.shop_api_plugin.factory.product_view_factory" has a dependency on a non-existent service "app.factory.product_view_factory.inner".
```
Wouldn't I have to define `app.factory.product_view_factory.inner` somewhere first? My class is pretty much a carbon copy of your example, with the names changed:

```php
<?php

namespace App\Factory\Product;

use Sylius\Component\Core\Model\ChannelInterface;
use Sylius\Component\Core\Model\ProductInterface;
use Sylius\ShopApiPlugin\Factory\Product\ProductViewFactoryInterface;

use Sylius\ShopApiPlugin\View\Product\ProductView;

class ExtendedProductViewFactory implements ProductViewFactoryInterface
{
    private $innerProductViewFactory;

    public function __construct(ProductViewFactoryInterface $innerProductViewFactory)
    {
        $this->innerProductViewFactory = $innerProductViewFactory;
    }

    public function create(ProductInterface $product, ChannelInterface $channel, string $locale): ProductView
    {
        /** @var ProductView $productView */
        $productView = $this->innerProductViewFactory->create($product, $channel, $locale);

        $productView->manufacturer = $product->getManufacturer();

        return $productView;
    }
}

```

**Comment by mamazu** [comment] 2019-08-19 10:47
Looks good. I hope it also works as intended.

To answer your question: No you don't have to specify the inner factory, this name is generated when the class is getting decorated to still have access to it. So when you decorate the service `product_factory` the original service can still be reached with `product_factory.inner`. That is something that Symfony does for you.

**Comment by flindblom-ohmy** [comment] 2019-08-19 11:13
I had the wrong path in arguments. It was easier when I switched from dot format to namespace format.

```yaml
# Extend Shop API cart view to include custom parameters
    App\Factory\Product\ExtendedProductViewFactory:
        arguments: ['@App\Factory\Product\ExtendedProductViewFactory.inner']
        decorates: sylius.shop_api_plugin.factory.product_view_factory
```
This works and now I have a "slim" ExtendedProductViewFactory and a much better understanding of what is going on. Thanks a lot!

**Comment by mamazu** [comment] 2019-09-21 14:00
We have merged the cookbook which describes the current way ShopApi should be extended. So I will close it for now. If you still have any questions feel free to open another issue or a pull request with a better documentation.

**Closed by mamazu** 2019-09-21 14:00 UTC
Labels: Documentation
