### ISSUE TITLE
Add Product filtering

### ISSUE THREAD

**Issue by GregoireHebert** [Sylius/ShopApiPlugin#255] opened 2018-02-13 08:50 UTC
Sometimes you don't need to get a full collection of products contained in a taxon.
As an Shop-API user you might need to filter upon the resource attributes.

I propose to let the user filter directly through it's queries.
The format would be `?filters[{filterType}][{attribute}]={value}`

For any attribute or a custom one:
`GET /shop-api/taxon-products/FRUITS?channel=WEB_FR&filters[boolean][customAttribute]=true`

It should be possible to filter onto nested properties
`GET /shop-api/taxon-products/FRUITS?channel=WEB_FR&filters[boolean][variants.shippingRequired]=false`

I propose to start with a first filter (work done at 80% just a few unit tests to go):
* boolean

And if you like this addition, complete the system by these:
* text
* date
* numeric
* range
* exists
* order

I propose firstly to implement this for `ShowProductCatalogByTaxonCodeAction` and `ShowProductCatalogByTaxonSlugAction`

I am currently working on a PR for this.
The filtering system I am implementing here comes from the work done on [api-platform/core](https://github.com/api-platform/core/tree/master/src/Bridge/Doctrine/Orm/Filter)

I'll update this when the PR is ready.

**Comment by lchrusciel** [comment] 2018-02-14 07:46
Hello Gregorie!

Thanks for your feedback and contribution. I totally age it is a must-have for such an API. Nevertheless, I think that this logic should be executed by the appropriate tool - Elasticsearch for instance. (SyliusElasticSearchPlugin)[https://github.com/Sylius/SyliusElasticSearchPlugin] has such an integration.

I haven't had a chance to look at your code yet, but I'm afraid that it is quite complicated to execute proper queries on SQL database. Anyway, I promise you that I will review the code, but not earlier than 26th of February.

**Comment by GregoireHebert** [comment] 2018-02-14 08:26
Alright then :)
I'll continue to improve this PR and hopefully change your mind the 26th ;)

**Comment by GregoireHebert** [comment] 2018-03-05 09:07
ping @lchrusciel :)
If you don't mind take a look ? Just for me to know If I keep going this way, Or maybe propose it as a plugin alternative to the SyliusElasticSearchBundle.

**Comment by lchrusciel** [comment] 2018-03-09 22:43
Sorry for the delay. Many things required my attention in the meantime.

**Comment by mamazu** [comment] 2019-08-28 17:08
This filtering could also be achieved if we use a grid in the product API endpoint as suggested in #49

**Comment by mamazu** [comment] 2019-09-21 14:15
Duplicate of #49

**Closed by mamazu** 2019-09-21 14:15 UTC
