### ISSUE TITLE
expand for custom models

### ISSUE THREAD

**Issue by samanmohamadi** [Sylius/ShopApiPlugin#233] opened 2017-11-02 08:40 UTC
Is it possible to expand plugin to serve custom models ?

**Comment by lchrusciel** [comment] 2017-11-02 09:38
Depends on what are you asking for. Do you want to change a regular Sylius model(aka write model)? Do it regular Sylius way. If you want to change the output data(aka read model), then each view factory receives a view class FQCN in the constructor in order to build the base view. From this point, you have to possible solutions, either decorate default view factory and add something to it or provide your custom implementation of view factory. At the end, if you just want to hide something, then it can be achieved with JMS serializer.

**Comment by samanmohamadi** [comment] 2017-11-02 16:15
I have a custom model (aka supplier), how can I add this model to API and make it accessible from `/shop-api/suppliers `

**Comment by lchrusciel** [comment] 2017-11-02 19:53
I would recommend to create them by hand. Check one of query endpoints for inspirations(taxons or products). Basically, you should add the supplier regular Sylius way, to make it available in admin panel and just create a read-only model for shop(similar to taxon view and taxon view factory)

**Comment by pjedrzejewski** [comment] 2017-11-27 22:29
@samanmohamadi You could also use ResourceBundle to create this new endpoints. It is just routing, so it does not have to be created in a similar fashion like this plugin. (that being said, we recommend this approach for non-CRUD operations)

**Comment by mamazu** [comment] 2019-01-16 20:21
@samanmohamadi Did you manage to implement this or are there still questions open?

**Comment by lchrusciel** [comment] 2019-01-17 07:52
I would say, that it is known. Unless you have some business specific logic, you should use ResourceBundle routing generation. Once you need to process some business logic (like cart operations), please use command pattern instead.

**Comment by mamazu** [comment] 2019-02-01 08:32
Duplicate of the more verbose version #354

**Closed** 2019-02-01 14:22 UTC
