### ISSUE TITLE
Product stock issue

### ISSUE THREAD

**Issue by seriousTom** [Sylius/ShopApiPlugin#509] opened 2019-08-05 22:48 UTC
Hello,
I have a product A with one item available in stock. But I can add to the cart as many items as I want. Shouldn`t it be a validation which would throw an error that Product A stock is insufficient as it is in regular sylius shop?

**Comment by lchrusciel** [comment] 2019-08-09 14:21
It should be fixed indeed

**Comment by mamazu** [comment] 2019-11-23 15:28
Closing as a duplicate of #594

**Closed by mamazu** 2019-11-23 15:28 UTC
Labels: Bug
